
--DELETE FROM tblBrand; 
--DELETE FROM tblCabang; 
--DELETE FROM tblChannelGrade; 
--DELETE FROM tblChannelType; 
--DELETE FROM tblCluster; 
--DELETE FROM tblClusterBinaan; 
DELETE FROM tblDealer; 
DELETE FROM tblDelayEntry; 
DELETE FROM tblDenomVoucher; 
DELETE FROM tblGroup; 
DELETE FROM tblHoliday; 
--DELETE FROM tblJenisProduk; 
-- DELETE FROM tblKabupaten; 
-- DELETE FROM tblKecamatan; 
-- DELETE FROM tblKelurahan; 
DELETE FROM tblProduk; 
DELETE FROM tblPropinsi; 
DELETE FROM tblRange; 
DELETE FROM tblRoadline; 

DELETE FROM tblKunjunganBeliPerdana; 
DELETE FROM tblKunjunganBeliVoucherDiskon; 
DELETE FROM tblKunjunganBeliVoucherElektrik; 
DELETE FROM tblKunjunganBeliVoucherElektrikHari; 
DELETE FROM tblKunjunganBeliVoucherElektrikKaliSeminggu; 
DELETE FROM tblKunjunganBeliVoucherFisik; 
DELETE FROM tblKunjunganBeliVoucherHarga; 
DELETE FROM tblKunjunganHandlingComplaint; 
DELETE FROM tblKunjunganJualPerdana; 
DELETE FROM tblKunjunganJualVoucherFisik; 
DELETE FROM tblKunjunganJumlahJualPerdana; 
DELETE FROM tblKunjunganJumlahJualVoucherFisik; 
DELETE FROM tblKunjunganJumlahStockPerdana; 
DELETE FROM tblKunjunganLoyaltyProgram; 
DELETE FROM tblKunjunganSalesProgram; 
DELETE FROM tblkunjunganStarterPack; 
DELETE FROM tblKunjunganVoucherElektronikD; 
DELETE FROM tblKunjunganVoucherElektronikDP; 
DELETE FROM tblKunjunganVoucherElektronikDR; 
DELETE FROM tblKunjunganVoucherElektronikV; 
DELETE FROM tblKunjunganVoucherFisik; 
DELETE FROM tblKunjungan; 

-- DELETE FROM tblMall; 
-- DELETE FROM tblMitra; 
-- DELETE FROM tblOperator; 
-- DELETE FROM tblOperatorVE; 

DELETE FROM tblOutletBTSCoverage; 
DELETE FROM tblOutletCanvaserSubDealer; 
DELETE FROM tblOutletDistributor; 
DELETE FROM tblOutletImage; 
DELETE FROM tblOutletMitra; 
DELETE FROM tblOutletMitraCanvaser; 
DELETE FROM tblOutletMitraDealer; 
DELETE FROM tblOutletMitraOwnedDealer; 
DELETE FROM tblOutletNeonBox; 
DELETE FROM tblOutletNoRSSEV; 
DELETE FROM tblOutletPainting; 
DELETE FROM tblOutletPegawai; 
DELETE FROM tblOutletPembelianStock; 
DELETE FROM tblOutletPriceBoard; 
DELETE FROM tblOutletSignBoard; 
DELETE FROM tblOutlet; 


DELETE FROM tblSeq; 
DELETE FROM tblSkalaBeliVoucherElektronik; 
DELETE FROM tblSkalaHargaBeliPerdana; 
DELETE FROM tblSkalaHargaBeliVoucherFisik; 
DELETE FROM tblSkalaHargaJualPerdana; 
DELETE FROM tblSkalaHargaJualVoucherFisik; 
DELETE FROM tblSkalaJumlahJualPerdana; 
DELETE FROM tblSkalaJumlahJualVoucherFisik; 
DELETE FROM tblSkalaJumlahStockPerdana; 
DELETE FROM tblStarterPack; 
-- DELETE FROM tblTipeSel; 
-- DELETE FROM tblTipeVoucher; 
-- DELETE FROM tblUser; 
-- DELETE FROM tblUserAction; 
-- DELETE FROM tblUserGroup; 
-- DELETE FROM tblUserPosition; 
-- DELETE FROM tblUserT; 
DELETE FROM tblVoucherElektronik; 
DELETE FROM tblVoucherFisik; 
DELETE FROM tblWilayahReps; 

----  -----------------------------------------------------------------------------------------------------------------------------------------------------------
--DBCC CHECKIDENT (tblBrand, RESEED, 1); 
--DBCC CHECKIDENT (tblCabang, RESEED, 1); 
--DBCC CHECKIDENT (tblChannelGrade, RESEED, 1); 
--DBCC CHECKIDENT (tblChannelType, RESEED, 1); 
--DBCC CHECKIDENT (tblCluster, RESEED, 1); 
--DBCC CHECKIDENT (tblClusterBinaan, RESEED, 1); 
DBCC CHECKIDENT (tblDealer, RESEED, 1); 
DBCC CHECKIDENT (tblDelayEntry, RESEED, 1); 
DBCC CHECKIDENT (tblDenomVoucher, RESEED, 1); 
DBCC CHECKIDENT (tblGroup, RESEED, 1); 
DBCC CHECKIDENT (tblHoliday, RESEED, 1); 
DBCC CHECKIDENT (tblJenisProduk, RESEED, 1); 
DBCC CHECKIDENT (tblKabupaten, RESEED, 1); 
DBCC CHECKIDENT (tblKecamatan, RESEED, 1); 
DBCC CHECKIDENT (tblKelurahan, RESEED, 1); 

DBCC CHECKIDENT (tblKunjungan, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganBeliPerdana, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganBeliVoucherDiskon, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganBeliVoucherElektrik, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganBeliVoucherElektrikHari, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganBeliVoucherElektrikKaliSeminggu, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganBeliVoucherFisik, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganBeliVoucherHarga, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganHandlingComplaint, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganJualPerdana, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganJualVoucherFisik, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganJumlahJualPerdana, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganJumlahJualVoucherFisik, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganJumlahStockPerdana, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganLoyaltyProgram, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganSalesProgram, RESEED, 1); 
DBCC CHECKIDENT (tblkunjunganStarterPack, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganVoucherElektronikD, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganVoucherElektronikDP, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganVoucherElektronikDR, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganVoucherElektronikV, RESEED, 1); 
DBCC CHECKIDENT (tblKunjunganVoucherFisik, RESEED, 1); 

DBCC CHECKIDENT (tblMall, RESEED, 1); 
DBCC CHECKIDENT (tblMitra, RESEED, 1); 
DBCC CHECKIDENT (tblOperator, RESEED, 1); 
DBCC CHECKIDENT (tblOperatorVE, RESEED, 1); 

DBCC CHECKIDENT (tblOutlet, RESEED, 1); 
DBCC CHECKIDENT (tblOutletBTSCoverage, RESEED, 1); 
DBCC CHECKIDENT (tblOutletCanvaserSubDealer, RESEED, 1); 
DBCC CHECKIDENT (tblOutletDistributor, RESEED, 1); 
DBCC CHECKIDENT (tblOutletImage, RESEED, 1); 
DBCC CHECKIDENT (tblOutletMitra, RESEED, 1); 
DBCC CHECKIDENT (tblOutletMitraCanvaser, RESEED, 1); 
DBCC CHECKIDENT (tblOutletMitraDealer, RESEED, 1); 
DBCC CHECKIDENT (tblOutletMitraOwnedDealer, RESEED, 1); 
DBCC CHECKIDENT (tblOutletNeonBox, RESEED, 1); 
DBCC CHECKIDENT (tblOutletNoRSSEV, RESEED, 1); 
DBCC CHECKIDENT (tblOutletPainting, RESEED, 1); 
DBCC CHECKIDENT (tblOutletPegawai, RESEED, 1); 
DBCC CHECKIDENT (tblOutletPembelianStock, RESEED, 1); 
DBCC CHECKIDENT (tblOutletPriceBoard, RESEED, 1); 
DBCC CHECKIDENT (tblOutletSignBoard, RESEED, 1); 


DBCC CHECKIDENT (tblProduk, RESEED, 1); 
DBCC CHECKIDENT (tblPropinsi, RESEED, 1); 
DBCC CHECKIDENT (tblRange, RESEED, 1); 
DBCC CHECKIDENT (tblRoadline, RESEED, 1); 
DBCC CHECKIDENT (tblSeq, RESEED, 1); 

DBCC CHECKIDENT (tblSkalaBeliVoucherElektronik, RESEED, 1); 
DBCC CHECKIDENT (tblSkalaHargaBeliPerdana, RESEED, 1); 
DBCC CHECKIDENT (tblSkalaHargaBeliVoucherFisik, RESEED, 1); 
DBCC CHECKIDENT (tblSkalaHargaJualPerdana, RESEED, 1); 
DBCC CHECKIDENT (tblSkalaHargaJualVoucherFisik, RESEED, 1); 
DBCC CHECKIDENT (tblSkalaJumlahJualPerdana, RESEED, 1); 
DBCC CHECKIDENT (tblSkalaJumlahJualVoucherFisik, RESEED, 1); 
DBCC CHECKIDENT (tblSkalaJumlahStockPerdana, RESEED, 1); 

DBCC CHECKIDENT (tblStarterPack, RESEED, 1); 
DBCC CHECKIDENT (tblTipeSel, RESEED, 1); 
DBCC CHECKIDENT (tblTipeVoucher, RESEED, 1); 
DBCC CHECKIDENT (tblUser, RESEED, 1); 
DBCC CHECKIDENT (tblUserAction, RESEED, 1); 
DBCC CHECKIDENT (tblUserGroup, RESEED, 1); 
DBCC CHECKIDENT (tblUserPosition, RESEED, 1); 
DBCC CHECKIDENT (tblUserT, RESEED, 1); 
DBCC CHECKIDENT (tblVoucherElektronik, RESEED, 1); 
DBCC CHECKIDENT (tblVoucherFisik, RESEED, 1); 
DBCC CHECKIDENT (tblWilayahReps, RESEED, 1); 
